#include <cassert>
#include <cstring>
#include <sstream>
#include <iostream>
#include <format>
#include <string>
#include <string_view>
#include <vector>
#include <array>
#include <deque>
#include <queue>
#include <stack>
#include <unordered_map>
#include <unordered_set>
#include <optional>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <limits>
#include <cstdint>
#include <functional>
#include <algorithm>

using std::cout;
using std::endl;
using std::format;
using std::println;
using std::stringstream;
using std::istringstream;
using std::ostringstream;
using namespace std::string_view_literals;

using std::pair;
using std::tuple;
using std::optional;
using std::string;
using std::string_view;
using std::vector;
using std::deque;
using std::queue;
using std::stack;
using std::array;
using std::unordered_map;
using std::unordered_set;
using std::numeric_limits;
